# build environment
FROM node:latest as build
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

RUN npm install react-scripts@3.4.1 -g --silent

ARG REACT_APP_IP
ENV REACT_APP_IP=$REACT_APP_IP

COPY package.json ./
COPY package-lock.json ./
RUN npm i --silent --production
COPY . ./
RUN npm run build

# production environment
FROM nginx
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]