export const SIGN_IN = `SIGN_IN`;
export const SIGN_IN_SUCCESS = `SIGN_IN_SUCCESS`;
export const SIGN_IN_FAILED = `SIGN_IN_FAILED`;

export const GET_BOOKS = `GET_BOOKS`;
export const BOOKS_RECEIVED = `BOOKS_RECEIVED`;
export const BOOKS_FAILED = `BOOKS_FAILED`;

export const GET_FAQ = `GET_FAQ`;
export const FAQ_RECEIVED = `FAQ_RECEIVED`;
export const FAQ_FAILED = `FAQ_FAILED`;

export const GET_RECOMMENDED_BOOKS = `GET_RECOMMENDED_BOOKS`;
export const RECOMMENDED_BOOKS_RECEIVED = `RECOMMENDED_BOOKS_RECEIVED`;
export const RECOMMENDED_BOOKS_FAILED = `RECOMMENDED_BOOKS_FAILED`;

export const GET_BOOK = `GET_BOOK`;
export const BOOK_RECEIVED = `BOOK_RECEIVED`;
export const BOOK_FAILED = `BOOK_FAILED`;

export const GET_CATEGORIES = `GET_CATEGORIES`;
export const CATEGORIES_RECEIVED = `CATEGORIES_RECEIVED`;
export const CATEGORIES_FAILED = `CATEGORIES_FAILED`;

export const GET_FAVORITES = `GET_FAVORITES`;
export const FAVORITES_RECEIVED = `FAVORITES_RECEIVED`;
export const FAVORITES_FAILED = `FAVORITES_FAILED`;

export const GET_USER = `GET_USER`;
export const USER_RECEIVED = `USER_RECEIVED`;
export const USER_FAILED = `USER_FAILED`;

export const GET_LANGUAGES = `GET_LANGUAGES`;
export const LANGUAGES_RECEIVED = `LANGUAGES_RECEIVED`;
export const LANGUAGES_FAILED = `LANGUAGES_FAILED`;

export const GET_AUTHORS = `GET_AUTHORS`;
export const AUTHORS_RECEIVED = `AUTHORS_RECEIVED`;
export const AUTHORS_FAILED = `AUTHORS_FAILED`;

export const GET_BOOK_PDF = `GET_BOOK_PDF`;
export const BOOK_PDF_RECEIVED = `BOOK_PDF_RECEIVED`;
export const BOOK_PDF_FAILED = `BOOK_PDF_FAILED`;

export const GET_REVIEWS = `GET_REVIEWS`;
export const REVIEWS_RECEIVED = `REVIEWS_RECEIVED`;
export const REVIEWS_FAILED = `REVIEWS_FAILED`;

export const GET_STATISTICS = `GET_STATISTICS`;
export const STATISTICS_RECEIVED = `STATISTICS_RECEIVED`;
export const STATISTICS_FAILED = `STATISTICS_FAILED`;

export const GET_UNI_REVIEWS = `GET_UNI_REVIEWS`;
export const UNI_REVIEWS_RECEIVED = `UNI_REVIEWS_RECEIVED`;
export const UNI_REVIEWS_FAILED = `UNI_REVIEWS_FAILED`;

export const GET_CATEGORIES_SEARCH = `GET_CATEGORIES_SEARCH`;
export const SEARCH_CATEGORIES_RECEIVED = `SEARCH_CATEGORIES_RECEIVED`;
export const SEARCH_CATEGORIES_FAILED = `SEARCH_CATEGORIES_FAILED`;

export const ADD_REVIEW = `ADD_REVIEW`;
export const ADD_REVIEW_SUCCESS = `ADD_REVIEW_SUCCESS`;
export const ADD_REVIEW_FAILED = `ADD_REVIEW_FAILED`;

export const ADD_REQUEST = `ADD_REQUEST`;
export const ADD_REQUEST_SUCCESS = `ADD_REQUEST_SUCCESS`;
export const ADD_REQUEST_FAILED = `ADD_REQUEST_FAILED`;

export const CHANGE_PASSWORD = `CHANGE_PASSWORD`;
export const PASSWORD_CHANGED = `PASSWORD_CHANGED`;
export const PASSWORD_FAILED = `PASSWORD_FAILED`;

export const ADD_FAVORITE = `ADD_FAVORITE`;
export const ADD_FAVORITE_SUCCESS = `ADD_FAVORITE_SUCCESS`;
export const ADD_FAVORITE_FAILED = `ADD_FAVORITE_FAILED`;


export const SIGN_OUT = `SIGN_OUT`;

export const SET_CURRENT_USER = `SET_CURRENT_USER`;